apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wms-ingress
  namespace: wms
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:648098100376:certificate/492135a9-f903-4e71-879d-e485939eff64
spec:
  ingressClassName: alb
  rules:
  - host: app.datanetwork.online
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: /uploads
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
